### ISSUE TITLE
add projects page

### ISSUE THREAD

**Issue by Discmonkey** [Discmonkey/retext#19]
Get started on following.

Will also need to extend interface on backend. And link projects to files / categories.

![image](https://user-images.githubusercontent.com/8137790/87736532-5acb6880-c7a6-11ea-9aa6-54cd829489e3.png)

**Comment by AleahGoldin** [comment]
I don't think we actually need that search at the top of this page. Unless... would that actually help users? Could we just list the projects out from newest to oldest?
