### ISSUE TITLE
View coding buckets

### ISSUE THREAD

**Issue by AleahGoldin** [Discmonkey/retext#39]
![Screen Shot 2020-08-04 at 7 26 08 PM](https://user-images.githubusercontent.com/34405164/89355040-6533a080-d688-11ea-8642-eb0b0f47b488.png)

We need to figure out what we should do for subcodes here... like how will they be displayed? Maybe you have a page that just takes you one level deeper that looks the same as this

**Comment by Discmonkey** [comment]
What's the percentage here? Number of documents with at least one code from each one?
